#!/usr/bin/env python3
"""Turn book/main.toc into docs/js/pagemap.js.

The quiz needs to know which PDF page every topic is on. Rather than hard-coding
page numbers into the question bank, questions reference a section by its exact
title and this script resolves the title to a page at build time. If the book
gains a page, the map regenerates and nothing else has to change.

Usage:  python3 tools/make-pagemap.py [book/main.toc] [docs/js/pagemap.js]
"""
import json
import re
import sys
from pathlib import Path

toc_path = Path(sys.argv[1] if len(sys.argv) > 1 else "book/main.toc")
out_path = Path(sys.argv[2] if len(sys.argv) > 2 else "docs/js/pagemap.js")

if not toc_path.exists():
    sys.exit(f"not found: {toc_path} — build the book first")

SECTION = re.compile(
    r"\\contentsline\s*\{section\}\{\\numberline\s*\{(\d+)\}(.*?)\}\{(\d+)\}"
)
PART = re.compile(r"\\contentsline\s*\{chapter\}\{(.*?)\}\{(\d+)\}")


def clean(text):
    """Strip the LaTeX that survives into the toc."""
    text = re.sub(r"\\IeC\s*", "", text)
    text = text.replace("\\&", "&")
    text = re.sub(r"\\[a-zA-Z]+\s*", "", text)
    text = text.replace("{", "").replace("}", "")
    text = text.replace("---", "\u2014").replace("--", "\u2013")
    return " ".join(text.split())


parts = []
for line in toc_path.read_text(encoding="utf-8").splitlines():
    m = SECTION.search(line)
    if m:
        if not parts:
            continue
        parts[-1]["sections"].append(
            {"n": int(m.group(1)), "title": clean(m.group(2)), "page": int(m.group(3))}
        )
        continue
    m = PART.search(line)
    if m:
        label = clean(m.group(1))
        num, _, title = label.partition(".")
        parts.append(
            {
                "id": num.strip(),
                "title": title.strip() or label,
                "page": int(m.group(2)),
                "sections": [],
            }
        )

if not parts:
    sys.exit("no parts found in the toc")

total = sum(len(p["sections"]) for p in parts)

# The PDF's physical page 1 is the title page, so a printed page number and a
# PDF page number differ by the length of the front matter. The app needs that
# offset to build a working  book.pdf#page=N  link.
offset = 0
pdf_path = toc_path.with_suffix(".pdf")
if pdf_path.exists():
    import subprocess

    try:
        info = subprocess.run(
            ["pdfinfo", str(pdf_path)], capture_output=True, text=True, check=True
        ).stdout
        physical = int(re.search(r"^Pages:\s+(\d+)", info, re.M).group(1))
        last_printed = max(s["page"] for p in parts for s in p["sections"])
        offset = physical - last_printed
    except Exception as exc:  # pdfinfo missing or unreadable PDF
        print(f"  (could not read {pdf_path}: {exc}; offset left at 0)")

payload = {"parts": parts, "sectionCount": total, "frontMatterOffset": offset}

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(
    "// Generated by tools/make-pagemap.py — do not edit by hand.\n"
    "window.PAGEMAP = "
    + json.dumps(payload, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"{out_path}: {len(parts)} parts, {total} sections")
